// Status Icons
import { InformationCircleIcon } from "@heroicons/react/outline";
import {
  CalendarIcon,
  CashIcon,
  CheckCircleIcon as CheckSolidIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClipboardListIcon,
  ClockIcon,
  DocumentDuplicateIcon,
  ExclamationCircleIcon,
  GlobeAltIcon as GlobeIcon,
  LinkIcon,
  PencilIcon,
  QuestionMarkCircleIcon as SolidQuestionMarkCircleIcon,
  SparklesIcon,
  StarIcon,
  UsersIcon,
  UserGroupIcon,
  XCircleIcon as XSolidIcon,
  XIcon,
  PlusIcon,
} from "@heroicons/react/solid";

enum HeroiconsType {
  CALENDAR = "calendar",
  CASH = "cash",
  CHECK = "check",
  CHEVRON_LEFT = "chevron-left",
  CLIPBOARD_LIST = "clipboardList",
  CLOCK = "clock",
  DOCUMENT_DUPLICATE = "document-duplicate",
  PENCIL = "pencil",
  EXCLAMATION_CIRCLE = "exclamation-circle",
  LINK = "link",
  PLUS = "plus",
  GLOBE = "globe",
  INFORMATION_CIRCLE = "informationCircle",
  SOLID_CHECK = "solid-check",
  SOLID_QUESTION_MARK_CIRCLE = "questionMarkCircle",
  SOLID_X = "solid-x",
  SPARKLES = "sparkles",
  STAR = "star",
  USERS = "users",
  USER_GROUP = "user-group",
  X = "x",
}

const heroiconsComponents: Record<HeroiconsType, React.FC<React.SVGProps<SVGSVGElement>>> = {
  calendar: CalendarIcon,
  cash: CashIcon,
  check: CheckIcon,
  "chevron-left": ChevronLeftIcon,
  clipboardList: ClipboardListIcon,
  clock: ClockIcon,
  "document-duplicate": DocumentDuplicateIcon,
  pencil: PencilIcon,
  "exclamation-circle": ExclamationCircleIcon,
  informationCircle: InformationCircleIcon,
  globe: GlobeIcon,
  link: LinkIcon,
  plus: PlusIcon,
  questionMarkCircle: SolidQuestionMarkCircleIcon,
  "solid-check": CheckSolidIcon,
  sparkles: SparklesIcon,
  star: StarIcon,
  users: UsersIcon,
  "user-group": UserGroupIcon,
  "solid-x": XSolidIcon,
  x: XIcon,
};

const heroIcons = Object.keys(heroiconsComponents).sort((a, b) =>
  a.localeCompare(b),
) as HeroiconsType[];

export {
  CalendarIcon,
  CheckSolidIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClipboardListIcon,
  ClockIcon,
  DocumentDuplicateIcon,
  ExclamationCircleIcon,
  InformationCircleIcon,
  GlobeIcon,
  LinkIcon,
  PlusIcon,
  SolidQuestionMarkCircleIcon,
  SparklesIcon,
  StarIcon,
  UserGroupIcon,
  XSolidIcon,
  XIcon,
};

export { heroiconsComponents, HeroiconsType, heroIcons };
